Waggle/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Waggle.Filters;
using Waggle.Models;
using Waggle.ViewModels;
using WebMatrix.WebData;


namespace Waggle.Controllers
{
    public class ForumController : Controller
    {
        private ForumContext db = new ForumContext();
        [InitializeSimpleMembershipAttribute]
        public ActionResult Index()
        {
            //These create lists of Forums, Topics, and Posts used for testing until the database is up.
           // Forum.SetUpForumList(); //A list of all forums.
            //Topic.SetUpTopicList(); //A list of all Topics.
           // Post.SetUpPostList(); //A list of all posts

            //This will need to be changed to something that includes user information
            //Because some forums are private and there will be different options based whether they are an admin

            return View(db.Forums.ToList());
        }

        [Authorize]
        public ActionResult DeleteForum(int forumID)
        {
            if (User.IsInRole("admin"))
            {
                using (ForumContext Fdb = new ForumContext())
                {
                    foreach (Forum f in Fdb.Forums)
                    {
                        if (f.ForumId == forumID)
                        {
                            f.IsDeleted = true;

                            using (TopicContext Tdb = new TopicContext())
                            {
                                foreach (Topic t in Tdb.Topics)
                                {
                                    if (t.ForumId == forumID)
                                    {
                                        t.IsDeleted = true;

                                        int topicID = t.TopicId;

                                        using (PostContext Pdb = new PostContext())
                                        {
                                            foreach (Post p in Pdb.Posts)
                                            {
                                                if (p.TopicId == topicID)
                                                {
                                                    p.IsDeleted = true;
                                                }
                                            }
                                            Pdb.SaveChanges();
                                        }
                                    }
                                }
                                Tdb.SaveChanges();
                            }
                        }
                    }
                    Fdb.SaveChanges();
                }
                return RedirectToAction("Index", "Forum");
            }
            else
            {
                return RedirectToAction("Http404", "Error");
            }
        }


        [Authorize]
        public ActionResult UndeleteForum(int forumID)
        {
            if (User.IsInRole("admin"))
            {
                using (ForumContext Fdb = new ForumContext())
                {
                    foreach (Forum f in Fdb.Forums)
                    {
                        if (f.ForumId == forumID)
                        {
                            f.IsDeleted = false;

                            using (TopicContext Tdb = new TopicContext())
                            {
                                foreach (Topic t in Tdb.Topics)
                                {
                                    if (t.ForumId == forumID)
                                    {
                                        t.IsDeleted = false;

                                        int topicID = t.TopicId;

                                        using (PostContext Pdb = new PostContext())
                                        {
                                            foreach (Post p in Pdb.Posts)
                                            {
                                                if (p.TopicId == topicID)
                                                {
                                                    p.IsDeleted = false;
                                                }
                                            }
                                            Pdb.SaveChanges();
                                        }
                                    }
                                }
                                Tdb.SaveChanges();
                            }
                        }
                    }
                    Fdb.SaveChanges();

                    return RedirectToAction("Index", "Forum");
                }
            }
            else
            {
                return RedirectToAction("Http404", "Error");
            }
        }

        [Authorize]
        [InitializeSimpleMembershipAttribute]
        public ActionResult CreateForum()
        {
            if (User.IsInRole("admin"))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Forbidden", "Admin");
            }
        }

        [HttpPost]
        [Authorize]
        [InitializeSimpleMembership]
        public ActionResult CreateForum(AdminPanel model)
        {
            if (User.IsInRole("admin"))
            {
                if (ModelState.IsValid)
                {
                    using (ForumContext Fdb = new ForumContext())
                    {
                        Forum newforum = new Forum();

                        newforum.UserId = WebSecurity.CurrentUserId;
                        newforum.Name = model.forum.Name;
                        newforum.Description = model.forum.Description;
                        Fdb.Forums.Add(newforum);
                        Fdb.SaveChanges();
                        return RedirectToAction("Index", "Forum");
                    }
                }
                else
                    return View("Forbidden");
            }
            else
            {
                return RedirectToAction("Http404", "Error");
            }
        }

        [Authorize]
        public ActionResult EditForum(int ForumId)
        {
            if (User.IsInRole("admin"))
            {
                Forum model = null;
                using (ForumContext db = new ForumContext()) {
                    foreach (Forum forum in db.Forums) {
                        if (forum.ForumId == ForumId) {
                            model = forum;
                        }
                    }
                }
                return View(model);
            }
            else
            {
                return RedirectToAction("Forbidden", "Admin");
            }
        }

        [Authorize]
        public ActionResult TogglePrivacy(int forumId) {
            if (User.IsInRole("admin"))
            {
                Forum f = null;
                using (ForumContext db = new ForumContext())
                {
                    foreach (Forum forum in db.Forums)
                    {
                        if (forum.ForumId == forumId)
                        {
                            forum.IsPrivate = !forum.IsPrivate;
                            f = forum;
                        }
                    }
                    db.SaveChanges();
                    return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
                }             
            }
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        

        [HttpPost]
        [Authorize]
        public ActionResult SubmitEdit(Forum model)
        {
            if (User.IsInRole("admin"))
            {
                if (ModelState.IsValid)
                {
                    using (ForumContext Fdb = new ForumContext())
                    {
                        foreach (Forum f in Fdb.Forums)
                        {
                            if (f.ForumId == model.ForumId)
                            {
                                f.Name = model.Name;
                                f.Description = model.Description;
                            }
                        }
                        Fdb.SaveChanges();
                        return RedirectToAction("Index", "Forum", Fdb.Forums);
                    }

                }
                return RedirectToAction("Index", "Forum");
            }
            else
            {
                return RedirectToAction("Forbidden", "Admin");
            }
        }
    }
}

Waggle/Controllers/ForumPermissionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Security;
using Waggle.Filters;
using Waggle.Models;
using WebMatrix.WebData;

namespace Waggle.Controllers
{
    [InitializeSimpleMembershipAttribute]
    public class ForumPermissionController : Controller
    {
        [HttpPost]
        [Authorize]
        public ActionResult AddPermission(String userEmail, int forumId)
        {
            if (User.IsInRole("admin")) {
                int userId = -1;
                using (UserEntitiesContext db = new UserEntitiesContext()) {
                    foreach (User user in db.Users) {
                        if (user.Email == userEmail) {
                            userId = user.Id;
                        }
                    }
                }
                if (userId != -1)
                {
                    using (Forum_PermissionContext db = new Forum_PermissionContext())
                    {
                        foreach (Forum_Permission permission in db.Forum_Permissions)
                        {
                            if (permission.UserId == userId && permission.ForumId == forumId)
                            {
                                return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
                            }
                        }
                        Forum_Permission fp = new Forum_Permission();
                        fp.UserId = userId;
                        fp.ForumId = forumId;
                        db.Forum_Permissions.Add(fp);
                        db.SaveChanges();
                    }
                }
            }
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

        [Authorize]
        public ActionResult RemovePermission(int userId, int forumId)
        {
            if (User.IsInRole("admin"))
            {
                using (Forum_PermissionContext db = new Forum_PermissionContext())
                {
                    foreach (Forum_Permission permission in db.Forum_Permissions)
                    {
                        if (permission.UserId == userId && permission.ForumId == forumId)
                        {
                            db.Forum_Permissions.Remove(permission);
                        }
                    }
                    db.SaveChanges();
                }
            }
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }


    }
}

Waggle/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Waggle.Models;
using Waggle.ViewModels;
using WebMatrix.WebData;

namespace Waggle.Controllers
{
    public class TopicController : Controller
    {
        private PostContext Pdb = new PostContext();
        private TopicContext Tdb = new TopicContext();
        public static TopicPost tp { get; set; }
        public ActionResult Index(int ForumId)
        {
            //PostList is a View Model that should contain forum/topic info to pass on to the View.
            PostList topics = new PostList();
            List<Topic> topicsList = new List<Topic>();

            using (TopicContext dbTopics = new TopicContext())
            {
                foreach (Topic t in dbTopics.Topics)
                {
                    if (t.ForumId == ForumId)
                    {
                        topicsList.Add(t);
                    }
                }
            }
             
            topics.Topics = topicsList;
            topics.ForumId = ForumId; //The forum whose topics should be displayed
            //topics.ForumName = Forum.ForumList[ForumId].Name;

            using (ForumContext dbForums = new ForumContext())
            {
                foreach (Forum f in dbForums.Forums)
                {
                    if (f.ForumId == ForumId)
                    {
                        topics.ForumName = f.Name;
                        break;
                    }
                }
            }
            return View(topics);
        }

        [Authorize]
        public ActionResult CreateTopic(int ForumId)
        {
            Forum forum = null;
            using (ForumContext dbForums = new ForumContext())
            {
                foreach (Forum f in dbForums.Forums)
                {
                    if (f.ForumId == ForumId)
                    {
                        forum = f;
                        break;
                    }
                }
            }
            /*
            using (TopicContext dbTopics = new TopicContext())
            {
                foreach (Topic t in dbTopics.Topics)
                {
                    if (t.TopicId == topicId)
                    {
                        topic = t;
                        break;
                    }
                }
            }
             */
            tp = new TopicPost() { TopicForum = forum, NewPostUserId = WebSecurity.CurrentUserId };
            return View(tp);
        }
        public ActionResult TopicCreated(string PostBody, string TopicName)
        {
            Topic t = new Topic();
            t.UserId = tp.NewPostUserId;
            t.ForumId = tp.TopicForum.ForumId;
            t.Name = TopicName;
            t.IsDeleted = false;
            if (ModelState.IsValid)
            {
                Tdb.Topics.Add(t);
                Tdb.SaveChanges();
            }

            Post p = new Post();
            p.UserId = tp.NewPostUserId;
            //p.UserId = 31; //TEMP
            p.TopicId = t.TopicId;
            p.Body = PostBody;
            p.IsDeleted = false;
            p.PostTime = DateTime.Now.ToString();
            p.ReplyTo = -1;
            if (ModelState.IsValid)
            {
                Pdb.Posts.Add(p);
                Pdb.SaveChanges();
                return RedirectToAction("Index", new { ForumId = t.ForumId });
            }
            return View();
        }

    }
}

Waggle/Views/Forum/CreateForum.cshtml
@model Waggle.ViewModels.AdminPanel

@{
    ViewBag.Title = "CreateForum";
}


<h2>Create New Forum</h2>
<br />
@using (Html.BeginForm())
{

    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.forum.Name)
                @Html.TextBoxFor(m => m.forum.Name)
            </li>
            <li>
                @Html.LabelFor(m => m.forum.Description)
                @Html.TextBoxFor(m => m.forum.Description)
            </li>
        </ol>
        <input type="submit" value="Create Forum" />
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Waggle/Views/Forum/EditForum.cshtml
@model Waggle.Models.Forum
@{
    ViewBag.Title = "EditForum";
}
<div class="container">
    <div class="row">

        <div class="col-sm-3 col-md-6 col-lg-8">
            <h2>Edit Forum</h2>
            @using (Html.BeginForm("SubmitEdit", "Forum"))
            {

                <fieldset>
                    <legend>Edit Forum</legend>
                    <br />
                    <ol>
                        <li>
                            @Html.LabelFor(m => m.ForumId)
                            @Html.TextAreaFor(m => m.ForumId)
                        </li>
                    </ol>
                    <ol>
                        <li>
                            @Html.LabelFor(m => m.Name)
                            @Html.TextAreaFor(m => m.Name)
                        </li>
                    </ol>
                    <ol>
                        <li>
                            @Html.LabelFor(m => m.Description)
                            @Html.TextAreaFor(m => m.Description)
                        </li>
                    </ol>
                    <input type="submit" value="Save Changes" />
                </fieldset>
            }
      </div>
      <div class="col-sm-9 col-md-6 col-lg-4">
            <h1>Privacy/Permissions</h1>
            <br />
            <span style="font-size: 1.2em">Privacy Mode - </span>

            @if (Model.IsPrivate)
            {
                <b style="font-size: 1.2em">Private</b>
            }
            else
            {
                <b style="font-size: 1.2em">Public</b>

            }
            <br />
            @Html.ActionLink("Toggle Privacy", "TogglePrivacy", "Forum", new { forumId = Model.ForumId }, null)


            @if (Model.IsPrivate)
            {
                <h3>Permitted Users</h3>
                foreach (Waggle.Models.User user in Model.getPermittedUsers())
                {
                    <ul>
                        <li>@user.Email @Html.ActionLink("X", "RemovePermission", "ForumPermission", new { userId = user.Id, forumId = Model.ForumId }, null)</li>
                    </ul>
                }
                using (Html.BeginForm("AddPermission", "ForumPermission", new { forumId = Model.ForumId }))
                {
                    <label>User Email</label>
                    <input type="text" name="userEmail" />
                    <input type="submit" value="Add User" />
                }
            }
            </div>
        </div>
    </div>


            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

Waggle/Views/Forum/Index.cshtml
@model List<Waggle.Models.Forum>

@{
    ViewBag.Title = "Index";
}

<h2>Forum List</h2>
@if (User.IsInRole("admin"))
{
    <h3>@Html.ActionLink("Create Forum", "CreateForum", "Forum")</h3><br /><br />
}


@foreach (Waggle.Models.Forum f in Model)
{
    if (!f.IsDeleted && User.IsInRole("admin"))
    {
        @Html.ActionLink(f.Name, "Index", "Topic", new { ForumId = f.ForumId }, new { @style = "font-size:1.2em" })
    <br/>
        @f.Description 
     <br />
        @Html.ActionLink("Edit", "EditForum", "Forum", new { ForumId = f.ForumId }, new { @style = "font-size:.8em"})
        @Html.ActionLink("Delete", "DeleteForum", "Forum", new { ForumId = f.ForumId }, new { @style = "font-size:.8em" })
        <br /> <br />
    }
    else if (!f.IsDeleted && !User.IsInRole("admin"))
    {
        <br/>
        if (!f.IsPrivate || (f.IsPrivate && f.isUserPermited(WebSecurity.CurrentUserId))) {
               
            @Html.ActionLink(f.Name, "Index", "Topic", new { ForumId = f.ForumId }, null) <br />
            @f.Description <br />
        }

    }
}

@if (User.IsInRole("admin"))
{
    <h3>Admin View: List of deleted forums</h3>
    <br/>
    foreach (Waggle.Models.Forum f in Model)
    {

        if (f.IsDeleted)
        {
            @Html.ActionLink(f.Name, "Index", "Topic", new { ForumId = f.ForumId }, new { @style = "font-size: 1.2em; color: red" })
    
    <br/>
    @f.Description 
    <br />
            @Html.ActionLink("Undelete", "UndeleteForum", "Forum", new { ForumId = f.ForumId }, new { @style = "font-size:.8em" })
            <br /> <br />
        }
    }

}