Waggle/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Security;
using Waggle.Models;
using WebMatrix.WebData;

namespace Waggle.Controllers
{
    public class FileController : Controller
    {
        //
        // GET: /File/

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /File/Upload

        [Authorize]
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase uploadFile, int forumId)
        {
            if (uploadFile == null || uploadFile.ContentLength == 0)
            {
                ViewBag.uploadMessage = "Select a file to upload";
                return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
            }
            if (ModelState.IsValid)
            {
                var fileName = Path.GetFileName(uploadFile.FileName);
                var fileDisplayName = fileName;
                string extension = Path.GetExtension(uploadFile.FileName);
                string strPath = "~\\Uploads\\" + WebSecurity.CurrentUserId;
                var path = Path.Combine(Server.MapPath(strPath), fileName);

                //handles duplicate file names
                if (System.IO.File.Exists(path)) { 
                    int i = 1;
                    var originalName = fileName;
                    while (System.IO.File.Exists(path)) {
                        fileName = i + originalName;
                        path = Path.Combine(Server.MapPath(strPath), fileName);
                        i++;
                    }
                }
                uploadFile.SaveAs(path);
                ModelState.Clear();

                //save file information

                //define context
                using (FileEntitiesContext db = new FileEntitiesContext())
                {
                    //create new model
                    Waggle.Models.File newFile = new Waggle.Models.File();
                    
                    //give model it's attributes - populating columns
                    newFile.fileName = fileName;
                    newFile.Forum_Id = forumId;
                    newFile.fileDisplayName = fileDisplayName;
                    newFile.filePath = path;
                    newFile.fileType = extension;
                    newFile.User_Id = WebSecurity.CurrentUserId;
                    
                    //save row
                    db.Files.Add(newFile);
                    db.SaveChanges();
                }
                ViewBag.uploadMessage = "Your file was uploaded!";
                return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
            }
            else {
                ViewBag.uploadMessage = "Your file was could not be uploaded";
                return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
            }
        }

        public FileResult Download(int Id) {
            Waggle.Models.File file;
            using (FileEntitiesContext db = new FileEntitiesContext()) {
                file = db.Files.Find(Id);
            }
            if (file == null) {
                return null;
            }
            return File(file.filePath, System.Net.Mime.MediaTypeNames.Application.Octet, file.fileName);
        }

        [Authorize]
        public ActionResult Delete(int Id)
        {
            Waggle.Models.File file;
            using (FileEntitiesContext db = new FileEntitiesContext())
            {
                file = db.Files.Find(Id);
                if ((file.User_Id == WebSecurity.CurrentUserId || Roles.IsUserInRole("admin")) && file != null)
                {
                    db.Files.Remove(file);
                    db.SaveChanges();
                }
                else
                {
                    return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
                }
            }
            System.IO.File.Delete(file.filePath);
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

    }
}

Waggle/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Waggle.Filters;
using Waggle.Models;
using Waggle.ViewModels;
using WebMatrix.WebData;

namespace Waggle.Controllers
{
    public class PostController : Controller
    {
        private PostContext db = new PostContext();
        public static TopicPost tp  = new TopicPost();

         [InitializeSimpleMembershipAttribute]
        public ActionResult Index(int TopicId)
        {
            ViewData["currentUserId"] = WebSecurity.CurrentUserId;
            //PostList is a View Model that should contain forum/topic info to pass on to the View.
            PostList list = new PostList();

            Topic topic = null; //The topic whose posts need to be displayed.
            using (TopicContext dbTopics = new TopicContext())
            {
                foreach (Topic t in dbTopics.Topics)
                {
                    if (t.TopicId == TopicId)
                    {
                        topic = t;
                        break;
                    }
                }
            }
            if (topic != null)
            {
                list.TopicId = TopicId;
                list.TopicName = topic.Name;
                //list.ForumName = Forum.ForumList[topic.ForumId].Name; //The forum that the topic is in
                using (ForumContext dbForums = new ForumContext())
                {
                    foreach (Forum f in dbForums.Forums)
                    {
                        if (f.ForumId == topic.ForumId)
                        {
                            list.ForumName = f.Name;
                            tp.forumId = f.ForumId;
                        }
                    }
                }
                list.ForumId = topic.ForumId;
                List<Post> posts = new List<Post>();
                using (PostContext dbPosts = new PostContext())
                {
                    foreach (Post p in dbPosts.Posts)
                    {
                        if (p.TopicId == TopicId)
                        {
                            if (p.AttachmentId != 0)
                                p.findAttachment();
                            posts.Add(p);
                        }
                    }
                }
                list.Posts = posts;

                return View(list);
            }
            return View("ERROR"); //Show an error or something. The topicId given as a parameter to this method doesn't exist.
        }

        [Authorize]
        public ActionResult CreatePost(int topicId)
        {
            Topic topic = null;
            using (TopicContext dbTopics = new TopicContext())
            {
                foreach (Topic t in dbTopics.Topics)
                {
                    if (t.TopicId == topicId)
                    {
                        topic = t;
                        break;
                    }
                }
            }
            tp = new TopicPost() { PostTopic = topic, NewPostUserId = WebSecurity.CurrentUserId };
            return View(tp);
        }

        [HttpPost]
        public ActionResult PostCreated(string PostBody, HttpPostedFileBase uploadFile)
        {
            int attachmentId = 0;
             if (uploadFile != null) { 
                var fileName = Path.GetFileName(uploadFile.FileName);
                var fileDisplayName = fileName;
                string extension = Path.GetExtension(uploadFile.FileName);
                string strPath = "~\\Uploads\\" + WebSecurity.CurrentUserId;
                var path = Path.Combine(Server.MapPath(strPath), fileName);

                //handles duplicate file names
                if (System.IO.File.Exists(path)) { 
                    int i = 1;
                    var originalName = fileName;
                    while (System.IO.File.Exists(path)) {
                        fileName = i + originalName;
                        path = Path.Combine(Server.MapPath(strPath), fileName);
                        i++;
                    }
                }
                uploadFile.SaveAs(path);

                //save file information

                //define context
                using (FileEntitiesContext db = new FileEntitiesContext())
                {
                    int forumId = -1;
                    //create new model
                    Waggle.Models.File newFile = new Waggle.Models.File();
                    
                    //give model it's attributes - populating columns
                    newFile.fileName = fileName;
                    using (TopicContext tc = new TopicContext()) {
                        foreach (Topic t in tc.Topics) {
                            if (t.TopicId == tp.PostTopic.TopicId) {
                                forumId = t.ForumId;
                            }
                        }
                    }
                    newFile.Forum_Id = forumId;
                    newFile.fileDisplayName = fileDisplayName;
                    newFile.filePath = path;
                    newFile.fileType = extension;
                    newFile.User_Id = WebSecurity.CurrentUserId;
                    
                    //save row
                    db.Files.Add(newFile);
                    db.SaveChanges();
                    attachmentId = newFile.Id;
                }
             }

            Post p = new Post();
            p.UserId = tp.NewPostUserId;
            p.TopicId = tp.PostTopic.TopicId;
            p.Body = PostBody;
            p.IsDeleted = false;
            p.AttachmentId = attachmentId;
            // DateTime d = DateTime.Now;
            // string time = d.DayOfWeek + " " + d.Month + " " + d.day;
            p.PostTime = DateTime.Now.ToString();
            p.ReplyTo = -1;
            Debug.WriteLine(p.PostTime);
            if (ModelState.IsValid)
            {
                db.Posts.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index", new { TopicId = p.TopicId });
            }
            return View();
        }
        [Authorize]
        public ActionResult Reply(int TopicId, int PostId)
        {
            Topic topic = null;
            using (TopicContext dbTopics = new TopicContext())
            {
                foreach (Topic t in dbTopics.Topics)
                {
                    if (t.TopicId == TopicId)
                    {
                        topic = t;
                        break;
                    }
                }
            }
            tp = new TopicPost() { PostTopic = topic, NewPostUserId = WebSecurity.CurrentUserId, replyToPost = PostId };
            return View(tp);
        }

        public ActionResult ReplyCreated(string PostBody, HttpPostedFileBase uploadFile)
        {
            int attachmentId = 0;
            if (uploadFile != null)
            {
                var fileName = Path.GetFileName(uploadFile.FileName);
                var fileDisplayName = fileName;
                string extension = Path.GetExtension(uploadFile.FileName);
                string strPath = "~\\Uploads\\" + WebSecurity.CurrentUserId;
                var path = Path.Combine(Server.MapPath(strPath), fileName);

                //handles duplicate file names
                if (System.IO.File.Exists(path))
                {
                    int i = 1;
                    var originalName = fileName;
                    while (System.IO.File.Exists(path))
                    {
                        fileName = i + originalName;
                        path = Path.Combine(Server.MapPath(strPath), fileName);
                        i++;
                    }
                }
                uploadFile.SaveAs(path);

                //save file information

                //define context
                using (FileEntitiesContext db = new FileEntitiesContext())
                {
                    int forumId = -1;
                    //create new model
                    Waggle.Models.File newFile = new Waggle.Models.File();

                    //give model it's attributes - populating columns
                    newFile.fileName = fileName;
                    using (TopicContext tc = new TopicContext())
                    {
                        foreach (Topic t in tc.Topics)
                        {
                            if (t.TopicId == tp.PostTopic.TopicId)
                            {
                                forumId = t.ForumId;
                            }
                        }
                    }
                    newFile.Forum_Id = forumId;
                    newFile.fileDisplayName = fileDisplayName;
                    newFile.filePath = path;
                    newFile.fileType = extension;
                    newFile.User_Id = WebSecurity.CurrentUserId;

                    //save row
                    db.Files.Add(newFile);
                    db.SaveChanges();
                    attachmentId = newFile.Id;
                }
            }
            Post p = new Post();
            p.UserId = tp.NewPostUserId;
            p.TopicId = tp.PostTopic.TopicId;
            p.Body = PostBody;
            p.IsDeleted = false;
            p.AttachmentId = attachmentId;
            // DateTime d = DateTime.Now;
            // string time = d.DayOfWeek + " " + d.Month + " " + d.day;
            p.PostTime = DateTime.Now.ToString();
            p.ReplyTo = tp.replyToPost; //This is a top-level post, not a reply
            if (ModelState.IsValid)
            {
                db.Posts.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index", new { TopicId = p.TopicId });
            }
            return View();
        }

        [Authorize]
        public ActionResult Edit(int PostId)
        {
            PostContext dbPosts = new PostContext();

Waggle/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Waggle.Models;
using Waggle.ViewModels;
using WebMatrix.WebData;

namespace Waggle.Controllers
{
    public class TopicController : Controller
    {
        private PostContext Pdb = new PostContext();
        private TopicContext Tdb = new TopicContext();
        public static TopicPost tp { get; set; }
        public ActionResult Index(int ForumId)
        {
            //PostList is a View Model that should contain forum/topic info to pass on to the View.
            PostList topics = new PostList();
            List<Topic> topicsList = new List<Topic>();

            using (TopicContext dbTopics = new TopicContext())
            {
                foreach (Topic t in dbTopics.Topics)
                {
                    if (t.ForumId == ForumId)
                    {
                        topicsList.Add(t);
                    }
                }
            }
             
            topics.Topics = topicsList;
            topics.ForumId = ForumId; //The forum whose topics should be displayed
            //topics.ForumName = Forum.ForumList[ForumId].Name;

            using (ForumContext dbForums = new ForumContext())
            {
                foreach (Forum f in dbForums.Forums)
                {
                    if (f.ForumId == ForumId)
                    {
                        topics.ForumName = f.Name;
                        break;
                    }
                }
            }
            return View(topics);
        }

        [Authorize]
        public ActionResult CreateTopic(int ForumId)
        {
            Forum forum = null;
            using (ForumContext dbForums = new ForumContext())
            {
                foreach (Forum f in dbForums.Forums)
                {
                    if (f.ForumId == ForumId)
                    {
                        forum = f;
                        break;
                    }
                }
            }
            /*
            using (TopicContext dbTopics = new TopicContext())
            {
                foreach (Topic t in dbTopics.Topics)
                {
                    if (t.TopicId == topicId)
                    {
                        topic = t;
                        break;
                    }
                }
            }
             */
            tp = new TopicPost() { TopicForum = forum, NewPostUserId = WebSecurity.CurrentUserId };
            return View(tp);
        }
        public ActionResult TopicCreated(string PostBody, string TopicName)
        {
            Topic t = new Topic();
            t.UserId = tp.NewPostUserId;
            t.ForumId = tp.TopicForum.ForumId;
            t.Name = TopicName;
            t.IsDeleted = false;
            if (ModelState.IsValid)
            {
                Tdb.Topics.Add(t);
                Tdb.SaveChanges();
            }

            Post p = new Post();
            p.UserId = tp.NewPostUserId;
            //p.UserId = 31; //TEMP
            p.TopicId = t.TopicId;
            p.Body = PostBody;
            p.IsDeleted = false;
            p.PostTime = DateTime.Now.ToString();
            p.ReplyTo = -1;
            if (ModelState.IsValid)
            {
                Pdb.Posts.Add(p);
                Pdb.SaveChanges();
                return RedirectToAction("Index", new { ForumId = t.ForumId });
            }
            return View();
        }

    }
}

Waggle/Views/Post/CreatePost.cshtml
@model Waggle.ViewModels.TopicPost

@{
    ViewBag.Title = "CreatePost";
}

<h2>Create Post</h2>

@*Post Title: @Html.TextBox("Post Title") <br /><br />*@
@*Post Body:<br />@Html.EditorFor(model => model.NewPostBody)<br />

@Html.ActionLink("Create Post", "PostCreated", "Post", new { npb = Model.NewPostBody,  }, null)*@

@using (Html.BeginForm("PostCreated", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
     <textarea id="PostBody" name="PostBody"></textarea>
    <label for="uploadFile">Attach a File</label>
    <input type="file" name="uploadFile" />
    <input type="submit" id="btnSubmit" value="Create Post" />
}

@*<input type="button" value="Create Post" onclick="createPost(body)"/>

<script>
    function createPost(body) {
        
    }
</script>*@

Waggle/Views/Post/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}
<h2>Delete</h2>

Waggle/Views/Post/Edit.cshtml
 @model Waggle.Models.Post
 @{
     ViewBag.Title = "Edit";
     }
 <h2>Edit a Post</h2>

@using (Html.BeginForm("Edited", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <textarea id="PostBody" name="PostBody">@Model.Body</textarea>
    if (Model.attachment != null) { 
         Attachment: <br />
         @Html.ActionLink(Model.attachment.fileDisplayName, "Download", "File", new { Id = Model.attachment.Id }, null) @Html.ActionLink("Delete", "Delete", "File", new { Id = Model.attachment.Id }, null)
        <br/>
    }
    else {
        <label for="uploadFile">Attach a File</label>
        <input type="file" name="uploadFile" />
    }
    
    <input type="submit" id="btnSubmit" value="Edit Post" />
}

Waggle/Views/Post/Index.cshtml
@model Waggle.ViewModels.PostList

@{
    ViewBag.Title = "Index";
}

<h2>@Html.ActionLink("Home", "Index", "Forum") > @Html.ActionLink(Model.ForumName, "Index", "Topic", new { ForumId = @Model.ForumId }, null) > @Model.TopicName</h2>
<h3>@Html.ActionLink("Create Post", "CreatePost", "Post", new { TopicId = Model.TopicId }, null)</h3><br /><br />
@foreach (Waggle.Models.Post p in Model.Posts)
{
    if (p.ReplyTo < 0) //This is a top-level post, i.e. not a reply
    {
        Waggle.Models.User curUser = Waggle.Models.User.GetUserById(p.UserId);
        //if(p.IsDeleted && curUser.IsAdmin)
        //{
        //Show "This post is deleted. It and its replies cannot be seen by normal users."
        //}
        if (!p.IsDeleted) //or is admin
        {
            <p style="font-size:11px">
                <img src=@curUser.AvatarPath width="30" height="30" />

                @Html.ActionLink(@curUser.Name, "Show", "User", new { id = @curUser.Id }, null) at @p.PostTime
                @Html.ActionLink("Reply", "Reply", "Post", new { TopicId = Model.TopicId, PostId = p.PostId }, null)
                @if(curUser.Id == WebSecurity.CurrentUserId || Roles.IsUserInRole(WebSecurity.CurrentUserName,"admin"))
                {
                    @Html.ActionLink("Edit", "Edit", "Post", new { PostId = p.PostId }, null)
                    @Html.ActionLink("Delete", "Delete", "Post", new { PostId = p.PostId }, null)
                }
            </p>
            <p style="font-size:14px">
                @p.Body
            </p>
            if (p.attachment != null)
            {
                <p style="font-size:14px">
                    Attachment: <br />
                    @Html.ActionLink(p.attachment.fileDisplayName, "Download", "File", new { Id = p.attachment.Id }, null) @Html.ActionLink("Delete", "Delete", "File", new { Id = p.attachment.Id }, null)
                </p>
            }<br />
            @DisplayReplies(p)
            <br />
        }
    }
}

@helper DisplayReplies(Waggle.Models.Post p)
{
    List<Waggle.Models.Post> replies = Waggle.Models.Post.GetReplies(p);
    if (replies.Count <= 0)
    {
        return;
    }
    Waggle.Models.User poster = Waggle.Models.User.GetUserById(p.UserId);
    foreach (Waggle.Models.Post reply in replies)
    {
        Waggle.Models.User replier = Waggle.Models.User.GetUserById(reply.UserId);
        //if(reply.IsDeleted && replier.IsAdmin)
        //{
        //Show "This post is deleted. It and its replies cannot be seen by normal users."
        //}
        if (!reply.IsDeleted)
        {
            reply.findAttachment();
    
            <blockquote>
                <p style="font-size:11px">
                    <img src=@replier.AvatarPath width="30" height="30" />

                    @Html.ActionLink(@replier.Name, "Show", "User", new { id = @replier.Id }, null) at @reply.PostTime in response to @poster.Name
                    @Html.ActionLink("Reply", "Reply", "Post", new { TopicId = Model.TopicId, PostId = reply.PostId }, null)
                    @if (replier.Id == WebSecurity.CurrentUserId || Roles.IsUserInRole(WebSecurity.CurrentUserName,"admin")) 
                    {
                        @Html.ActionLink("Edit", "Edit", "Post", new { PostId = reply.PostId }, null)
                        @Html.ActionLink("Delete", "Delete", "Post", new { PostId = reply.PostId }, null)
                    }
                </p>
                <p style="font-size:14px">
                    @reply.Body
                </p>
                @if (reply.attachment != null) {
                <p style="font-size:14px">
                    Attachment: <br />
                    @Html.ActionLink(reply.attachment.fileDisplayName, "Download", "File", new { Id = reply.attachment.Id }, null) @Html.ActionLink("Delete", "Delete", "File", new { Id = reply.attachment.Id }, null)
                </p>

                }<br />
                
                @DisplayReplies(reply)
            </blockquote>
        }
    }
}
@if (User.IsInRole("admin"))
{
    <h3>Admin View: List of deleted posts</h3>

    foreach (Waggle.Models.Post p in Model.Posts)
    {
        if (p.IsDeleted)
        {
           Waggle.Models.User curUser = Waggle.Models.User.GetUserById(p.UserId);
            <p style="font-size:11px">
                <img src=@curUser.AvatarPath width="30" height="30" />

                @curUser.Name at @p.PostTime

                @Html.ActionLink("Undelete", "UndeletePost", "Post", new { PostId = p.PostId }, null)
            </p>
            <p style="font-size:14px">
                @p.Body
            </p>
            if (p.attachment != null) { 
                <p style="font-size:14px">Attachment: <br/>
                    @Html.ActionLink(p.attachment.fileDisplayName, "Download", "File", new { Id = p.attachment.Id }, null) @Html.ActionLink("Delete", "Delete", "File", new { Id = p.attachment.Id }, null)
                </p>

           }<br />
        }
    }
}

Waggle/Views/Post/PostCreated.cshtml
@{
    ViewBag.Title = "PostCreated";
}

<h2>PostCreated</h2>

Waggle/Views/Post/Reply.cshtml
@{
    ViewBag.Title = "Reply";
}

<h2>Reply to Post</h2>
@using (Html.BeginForm("ReplyCreated", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <textarea id="PostBody" name="PostBody"></textarea>
    <label for="uploadFile">Attach a File</label>
    <input type="file" name="uploadFile" />
    <input type="submit" id="btnSubmit" value="Reply" />
}